package com.as.dao;

import com.as.dataobject.AccessScores;

public interface AccessScoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int insert(AccessScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int insertSelective(AccessScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    AccessScores selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int updateByPrimaryKeySelective(AccessScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int updateByPrimaryKey(AccessScores record);
}