package com.as.dao;

import com.as.dataobject.AssessScores;
import com.as.dataobject.AssessScoresKey;

public interface AssessScoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessscores
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    int deleteByPrimaryKey(AssessScoresKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessscores
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    int insert(AssessScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessscores
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    int insertSelective(AssessScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessscores
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    AssessScores selectByPrimaryKey(AssessScoresKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessscores
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    int updateByPrimaryKeySelective(AssessScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessscores
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    int updateByPrimaryKey(AssessScores record);
}