package com.as.dao;

import com.as.dataobject.ComprehensiveScores;
import com.as.dataobject.ComprehensiveScoresKey;

import java.util.List;

public interface ComprehensiveScoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    int deleteByPrimaryKey(ComprehensiveScoresKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    int insert(ComprehensiveScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    int insertSelective(ComprehensiveScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    ComprehensiveScores selectByPrimaryKey(ComprehensiveScoresKey key);
    List<ComprehensiveScores> selectAllScores();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    int updateByPrimaryKeySelective(ComprehensiveScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    int updateByPrimaryKey(ComprehensiveScores record);
}