package com.as.dao;

import com.as.dataobject.ComprehensiveScores;

import java.util.List;

public interface ComprehensiveScoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);
    List<ComprehensiveScores> selectAllScores();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int insert(ComprehensiveScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int insertSelective(ComprehensiveScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    ComprehensiveScores selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int updateByPrimaryKeySelective(ComprehensiveScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comprehensivescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int updateByPrimaryKey(ComprehensiveScores record);
}