package com.as.dao;

import com.as.dataobject.PracticeScores;

public interface PracticeScoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int insert(PracticeScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int insertSelective(PracticeScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    PracticeScores selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int updateByPrimaryKeySelective(PracticeScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int updateByPrimaryKey(PracticeScores record);
}