package com.as.dao;

import com.as.dataobject.PracticeScores;
import com.as.dataobject.PracticeScoresKey;

public interface PracticeScoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    int deleteByPrimaryKey(PracticeScoresKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    int insert(PracticeScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    int insertSelective(PracticeScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    PracticeScores selectByPrimaryKey(PracticeScoresKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    int updateByPrimaryKeySelective(PracticeScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practicescores
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    int updateByPrimaryKey(PracticeScores record);
}