package com.as.dao;

import com.as.dataobject.QuestionnaireDetail;

import java.util.List;

public interface QuestionnaireDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairedetail
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    int deleteByPrimaryKey(Integer id);
    List<QuestionnaireDetail> getAllQuestionnaireDetail();
    List<QuestionnaireDetail> getQuestionnaireDetailById(int id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairedetail
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    int insert(QuestionnaireDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairedetail
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    int insertSelective(QuestionnaireDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairedetail
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    QuestionnaireDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairedetail
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    int updateByPrimaryKeySelective(QuestionnaireDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairedetail
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    int updateByPrimaryKey(QuestionnaireDetail record);
}