package com.as.dao;

import com.as.dataobject.QuestionnaireScores;
import com.as.dataobject.QuestionnaireScoresKey;

public interface QuestionnaireScoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    int deleteByPrimaryKey(QuestionnaireScoresKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    int insert(QuestionnaireScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    int insertSelective(QuestionnaireScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    QuestionnaireScores selectByPrimaryKey(QuestionnaireScoresKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    int updateByPrimaryKeySelective(QuestionnaireScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    int updateByPrimaryKey(QuestionnaireScores record);
}