package com.as.dao;

import com.as.dataobject.QuestionnaireScores;
import com.as.dataobject.QuestionnaireScoresKey;

import java.util.List;

public interface QuestionnaireScoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    int deleteByPrimaryKey(QuestionnaireScoresKey key);
    List<QuestionnaireScores> getAllQuestionnaireScoresBySid(String sid);
    List<QuestionnaireScores>  getAllQuestionnaireScores();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    int insert(QuestionnaireScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    int insertSelective(QuestionnaireScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    QuestionnaireScores selectByPrimaryKey(QuestionnaireScoresKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    int updateByPrimaryKeySelective(QuestionnaireScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnairescores
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    int updateByPrimaryKey(QuestionnaireScores record);
}