package com.as.dao;

import com.as.dataobject.StudyScores;

public interface StudyScoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int insert(StudyScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int insertSelective(StudyScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    StudyScores selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int updateByPrimaryKeySelective(StudyScores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscores
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int updateByPrimaryKey(StudyScores record);
}