package com.as.dao;

import com.as.dataobject.Student;

import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 17 13:05:37 CST 2020
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 17 13:05:37 CST 2020
     */
    int insert(Student record);
    List<String> selectSidsByMajorAndClazz(String major,String clazz);
    String selectNameBySid(String Sid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 17 13:05:37 CST 2020
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 17 13:05:37 CST 2020
     */
    Student selectByPrimaryKey(String sid);
    List<Student> selectAllStudents();
    Student selectBySid(String sid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 17 13:05:37 CST 2020
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 17 13:05:37 CST 2020
     */
    int updateByPrimaryKey(Student record);
}