package com.as.dao;

import com.as.dataobject.StudyScoreDetail2;

public interface StudyScoreDetail2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscoredetail2
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscoredetail2
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int insert(StudyScoreDetail2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscoredetail2
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int insertSelective(StudyScoreDetail2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscoredetail2
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    StudyScoreDetail2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscoredetail2
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int updateByPrimaryKeySelective(StudyScoreDetail2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studyscoredetail2
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    int updateByPrimaryKey(StudyScoreDetail2 record);
}