package com.as.dao;

import com.as.dataobject.TeacherClasses;

public interface TeacherClassesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherclasses
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherclasses
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    int insert(TeacherClasses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherclasses
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    int insertSelective(TeacherClasses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherclasses
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    TeacherClasses selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherclasses
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    int updateByPrimaryKeySelective(TeacherClasses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacherclasses
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    int updateByPrimaryKey(TeacherClasses record);
}