package com.as.dataobject;

public class AssessScores extends AssessScoresKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessscores.id
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessscores.score
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assessscores.isdelete
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessscores.id
     *
     * @return the value of assessscores.id
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessscores.id
     *
     * @param id the value for assessscores.id
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessscores.score
     *
     * @return the value of assessscores.score
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessscores.score
     *
     * @param score the value for assessscores.score
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assessscores.isdelete
     *
     * @return the value of assessscores.isdelete
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assessscores.isdelete
     *
     * @param isdelete the value for assessscores.isdelete
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}