package com.as.dataobject;

public class ComprehensiveScoresKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comprehensivescores.date
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comprehensivescores.Sid
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comprehensivescores.date
     *
     * @return the value of comprehensivescores.date
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comprehensivescores.date
     *
     * @param date the value for comprehensivescores.date
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comprehensivescores.Sid
     *
     * @return the value of comprehensivescores.Sid
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comprehensivescores.Sid
     *
     * @param sid the value for comprehensivescores.Sid
     *
     * @mbg.generated Mon Apr 20 13:21:31 CST 2020
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}