package com.as.dataobject;

public class ComprehensiveScores {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comprehensivescores.id
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comprehensivescores.date
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comprehensivescores.comprehensivescore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer comprehensivescore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comprehensivescores.studyscore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer studyscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comprehensivescores.practicescore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer practicescore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comprehensivescores.accessscore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer accessscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comprehensivescores.Sid
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comprehensivescores.isdelete
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comprehensivescores.name
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comprehensivescores.id
     *
     * @return the value of comprehensivescores.id
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comprehensivescores.id
     *
     * @param id the value for comprehensivescores.id
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comprehensivescores.date
     *
     * @return the value of comprehensivescores.date
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comprehensivescores.date
     *
     * @param date the value for comprehensivescores.date
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comprehensivescores.comprehensivescore
     *
     * @return the value of comprehensivescores.comprehensivescore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getComprehensivescore() {
        return comprehensivescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comprehensivescores.comprehensivescore
     *
     * @param comprehensivescore the value for comprehensivescores.comprehensivescore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setComprehensivescore(Integer comprehensivescore) {
        this.comprehensivescore = comprehensivescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comprehensivescores.studyscore
     *
     * @return the value of comprehensivescores.studyscore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getStudyscore() {
        return studyscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comprehensivescores.studyscore
     *
     * @param studyscore the value for comprehensivescores.studyscore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setStudyscore(Integer studyscore) {
        this.studyscore = studyscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comprehensivescores.practicescore
     *
     * @return the value of comprehensivescores.practicescore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getPracticescore() {
        return practicescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comprehensivescores.practicescore
     *
     * @param practicescore the value for comprehensivescores.practicescore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setPracticescore(Integer practicescore) {
        this.practicescore = practicescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comprehensivescores.accessscore
     *
     * @return the value of comprehensivescores.accessscore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getAccessscore() {
        return accessscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comprehensivescores.accessscore
     *
     * @param accessscore the value for comprehensivescores.accessscore
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setAccessscore(Integer accessscore) {
        this.accessscore = accessscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comprehensivescores.Sid
     *
     * @return the value of comprehensivescores.Sid
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comprehensivescores.Sid
     *
     * @param sid the value for comprehensivescores.Sid
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comprehensivescores.isdelete
     *
     * @return the value of comprehensivescores.isdelete
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comprehensivescores.isdelete
     *
     * @param isdelete the value for comprehensivescores.isdelete
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comprehensivescores.name
     *
     * @return the value of comprehensivescores.name
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comprehensivescores.name
     *
     * @param name the value for comprehensivescores.name
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}