package com.as.dataobject;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.id
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Mid
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.name
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.phone
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.email
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mode
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    private String mode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.id
     *
     * @return the value of manager.id
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.id
     *
     * @param id the value for manager.id
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Mid
     *
     * @return the value of manager.Mid
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Mid
     *
     * @param mid the value for manager.Mid
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.name
     *
     * @return the value of manager.name
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.name
     *
     * @param name the value for manager.name
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.phone
     *
     * @return the value of manager.phone
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.phone
     *
     * @param phone the value for manager.phone
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.email
     *
     * @return the value of manager.email
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.email
     *
     * @param email the value for manager.email
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mode
     *
     * @return the value of manager.mode
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mode
     *
     * @param mode the value for manager.mode
     *
     * @mbg.generated Thu Apr 16 14:59:47 CST 2020
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }
}