package com.as.dataobject;

public class PracticeScores extends PracticeScoresKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practicescores.id
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practicescores.score
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practicescores.isdelete
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    private Integer isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practicescores.name
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practicescores.id
     *
     * @return the value of practicescores.id
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practicescores.id
     *
     * @param id the value for practicescores.id
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practicescores.score
     *
     * @return the value of practicescores.score
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practicescores.score
     *
     * @param score the value for practicescores.score
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practicescores.isdelete
     *
     * @return the value of practicescores.isdelete
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practicescores.isdelete
     *
     * @param isdelete the value for practicescores.isdelete
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practicescores.name
     *
     * @return the value of practicescores.name
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practicescores.name
     *
     * @param name the value for practicescores.name
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}