package com.as.dataobject;

public class QuestionnaireScoresKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.sid
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.sid1
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    private String sid1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.date
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.sid
     *
     * @return the value of questionnairescores.sid
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.sid
     *
     * @param sid the value for questionnairescores.sid
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.sid1
     *
     * @return the value of questionnairescores.sid1
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public String getSid1() {
        return sid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.sid1
     *
     * @param sid1 the value for questionnairescores.sid1
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public void setSid1(String sid1) {
        this.sid1 = sid1 == null ? null : sid1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.date
     *
     * @return the value of questionnairescores.date
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.date
     *
     * @param date the value for questionnairescores.date
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }
}