package com.as.dataobject;

public class QuestionnaireScores extends QuestionnaireScoresKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.score
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.date
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.score
     *
     * @return the value of questionnairescores.score
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.score
     *
     * @param score the value for questionnairescores.score
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.date
     *
     * @return the value of questionnairescores.date
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.date
     *
     * @param date the value for questionnairescores.date
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }
}