package com.as.dataobject;

public class Questionnaire {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire.qid
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    private Integer qid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire.name
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire.remark
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire.qid
     *
     * @return the value of questionnaire.qid
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire.qid
     *
     * @param qid the value for questionnaire.qid
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire.name
     *
     * @return the value of questionnaire.name
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire.name
     *
     * @param name the value for questionnaire.name
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire.remark
     *
     * @return the value of questionnaire.remark
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire.remark
     *
     * @param remark the value for questionnaire.remark
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}