package com.as.dataobject;

public class QuestionnaireScores extends QuestionnaireScoresKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.score
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.iscomplete
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    private String iscomplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.qid
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    private String qid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.toname
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    private String toname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.name
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.clazz
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    private String clazz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairescores.major
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    private String major;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.score
     *
     * @return the value of questionnairescores.score
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.score
     *
     * @param score the value for questionnairescores.score
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.iscomplete
     *
     * @return the value of questionnairescores.iscomplete
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public String getIscomplete() {
        return iscomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.iscomplete
     *
     * @param iscomplete the value for questionnairescores.iscomplete
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public void setIscomplete(String iscomplete) {
        this.iscomplete = iscomplete == null ? null : iscomplete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.qid
     *
     * @return the value of questionnairescores.qid
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public String getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.qid
     *
     * @param qid the value for questionnairescores.qid
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public void setQid(String qid) {
        this.qid = qid == null ? null : qid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.toname
     *
     * @return the value of questionnairescores.toname
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public String getToname() {
        return toname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.toname
     *
     * @param toname the value for questionnairescores.toname
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public void setToname(String toname) {
        this.toname = toname == null ? null : toname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.name
     *
     * @return the value of questionnairescores.name
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.name
     *
     * @param name the value for questionnairescores.name
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.clazz
     *
     * @return the value of questionnairescores.clazz
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.clazz
     *
     * @param clazz the value for questionnairescores.clazz
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairescores.major
     *
     * @return the value of questionnairescores.major
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairescores.major
     *
     * @param major the value for questionnairescores.major
     *
     * @mbg.generated Sun Apr 26 20:18:37 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }
}