package com.as.dataobject;

public class QuestionnaireDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairedetail.id
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairedetail.qid
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    private Integer qid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnairedetail.question
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    private String question;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairedetail.id
     *
     * @return the value of questionnairedetail.id
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairedetail.id
     *
     * @param id the value for questionnairedetail.id
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairedetail.qid
     *
     * @return the value of questionnairedetail.qid
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairedetail.qid
     *
     * @param qid the value for questionnairedetail.qid
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnairedetail.question
     *
     * @return the value of questionnairedetail.question
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnairedetail.question
     *
     * @param question the value for questionnairedetail.question
     *
     * @mbg.generated Tue Apr 21 16:57:31 CST 2020
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }
}