package com.as.dataobject;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sid
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.major
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.clazz
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String clazz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.e-mail
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String eMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.delete
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private Integer delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mode
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String mode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sid
     *
     * @return the value of student.Sid
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sid
     *
     * @param sid the value for student.Sid
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.major
     *
     * @return the value of student.major
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.major
     *
     * @param major the value for student.major
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.clazz
     *
     * @return the value of student.clazz
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.clazz
     *
     * @param clazz the value for student.clazz
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.e-mail
     *
     * @return the value of student.e-mail
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.e-mail
     *
     * @param eMail the value for student.e-mail
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.delete
     *
     * @return the value of student.delete
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.delete
     *
     * @param delete the value for student.delete
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mode
     *
     * @return the value of student.mode
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mode
     *
     * @param mode the value for student.mode
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }
}