package com.as.dataobject;

public class StudyScoreDetail2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscoredetail2.id
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscoredetail2.Sid
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscoredetail2.makesi
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer makesi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscoredetail2.junshililun
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer junshililun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscoredetail2.xianxingdaishu
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer xianxingdaishu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscoredetail2.english
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer english;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscoredetail2.getiruanjian
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer getiruanjian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscoredetail2.lisanshuxue
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer lisanshuxue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscoredetail2.yingyongwenxiezuo
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer yingyongwenxiezuo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscoredetail2.gaodengshuxue
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer gaodengshuxue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscoredetail2.name
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscoredetail2.id
     *
     * @return the value of studyscoredetail2.id
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscoredetail2.id
     *
     * @param id the value for studyscoredetail2.id
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscoredetail2.Sid
     *
     * @return the value of studyscoredetail2.Sid
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscoredetail2.Sid
     *
     * @param sid the value for studyscoredetail2.Sid
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscoredetail2.makesi
     *
     * @return the value of studyscoredetail2.makesi
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getMakesi() {
        return makesi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscoredetail2.makesi
     *
     * @param makesi the value for studyscoredetail2.makesi
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setMakesi(Integer makesi) {
        this.makesi = makesi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscoredetail2.junshililun
     *
     * @return the value of studyscoredetail2.junshililun
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getJunshililun() {
        return junshililun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscoredetail2.junshililun
     *
     * @param junshililun the value for studyscoredetail2.junshililun
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setJunshililun(Integer junshililun) {
        this.junshililun = junshililun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscoredetail2.xianxingdaishu
     *
     * @return the value of studyscoredetail2.xianxingdaishu
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getXianxingdaishu() {
        return xianxingdaishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscoredetail2.xianxingdaishu
     *
     * @param xianxingdaishu the value for studyscoredetail2.xianxingdaishu
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setXianxingdaishu(Integer xianxingdaishu) {
        this.xianxingdaishu = xianxingdaishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscoredetail2.english
     *
     * @return the value of studyscoredetail2.english
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscoredetail2.english
     *
     * @param english the value for studyscoredetail2.english
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setEnglish(Integer english) {
        this.english = english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscoredetail2.getiruanjian
     *
     * @return the value of studyscoredetail2.getiruanjian
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getGetiruanjian() {
        return getiruanjian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscoredetail2.getiruanjian
     *
     * @param getiruanjian the value for studyscoredetail2.getiruanjian
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setGetiruanjian(Integer getiruanjian) {
        this.getiruanjian = getiruanjian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscoredetail2.lisanshuxue
     *
     * @return the value of studyscoredetail2.lisanshuxue
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getLisanshuxue() {
        return lisanshuxue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscoredetail2.lisanshuxue
     *
     * @param lisanshuxue the value for studyscoredetail2.lisanshuxue
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setLisanshuxue(Integer lisanshuxue) {
        this.lisanshuxue = lisanshuxue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscoredetail2.yingyongwenxiezuo
     *
     * @return the value of studyscoredetail2.yingyongwenxiezuo
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getYingyongwenxiezuo() {
        return yingyongwenxiezuo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscoredetail2.yingyongwenxiezuo
     *
     * @param yingyongwenxiezuo the value for studyscoredetail2.yingyongwenxiezuo
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setYingyongwenxiezuo(Integer yingyongwenxiezuo) {
        this.yingyongwenxiezuo = yingyongwenxiezuo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscoredetail2.gaodengshuxue
     *
     * @return the value of studyscoredetail2.gaodengshuxue
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getGaodengshuxue() {
        return gaodengshuxue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscoredetail2.gaodengshuxue
     *
     * @param gaodengshuxue the value for studyscoredetail2.gaodengshuxue
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setGaodengshuxue(Integer gaodengshuxue) {
        this.gaodengshuxue = gaodengshuxue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscoredetail2.name
     *
     * @return the value of studyscoredetail2.name
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscoredetail2.name
     *
     * @param name the value for studyscoredetail2.name
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}