package com.as.dataobject;

public class StudyScores {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscores.id
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscores.date
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscores.score
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscores.Sid
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscores.isdelete
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private Integer isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscores.name
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscores.id
     *
     * @return the value of studyscores.id
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscores.id
     *
     * @param id the value for studyscores.id
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscores.date
     *
     * @return the value of studyscores.date
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscores.date
     *
     * @param date the value for studyscores.date
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscores.score
     *
     * @return the value of studyscores.score
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscores.score
     *
     * @param score the value for studyscores.score
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscores.Sid
     *
     * @return the value of studyscores.Sid
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscores.Sid
     *
     * @param sid the value for studyscores.Sid
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscores.isdelete
     *
     * @return the value of studyscores.isdelete
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscores.isdelete
     *
     * @param isdelete the value for studyscores.isdelete
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscores.name
     *
     * @return the value of studyscores.name
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscores.name
     *
     * @param name the value for studyscores.name
     *
     * @mbg.generated Wed Apr 15 16:10:35 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}