package com.as.dataobject;

public class StudyScoresKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscores.date
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyscores.Sid
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    private String sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscores.date
     *
     * @return the value of studyscores.date
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscores.date
     *
     * @param date the value for studyscores.date
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyscores.Sid
     *
     * @return the value of studyscores.Sid
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyscores.Sid
     *
     * @param sid the value for studyscores.Sid
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }
}