package com.as.dataobject;

public class TeacherClasses {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherclasses.id
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherclasses.Tid
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacherclasses.clazz
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private Integer clazz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherclasses.id
     *
     * @return the value of teacherclasses.id
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherclasses.id
     *
     * @param id the value for teacherclasses.id
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherclasses.Tid
     *
     * @return the value of teacherclasses.Tid
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherclasses.Tid
     *
     * @param tid the value for teacherclasses.Tid
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacherclasses.clazz
     *
     * @return the value of teacherclasses.clazz
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public Integer getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacherclasses.clazz
     *
     * @param clazz the value for teacherclasses.clazz
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setClazz(Integer clazz) {
        this.clazz = clazz;
    }
}