package com.as.dataobject;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tid
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.phone
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.e-mail
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String eMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.delete
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.mode
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    private String mode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tid
     *
     * @return the value of teacher.Tid
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tid
     *
     * @param tid the value for teacher.Tid
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.phone
     *
     * @return the value of teacher.phone
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.phone
     *
     * @param phone the value for teacher.phone
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.e-mail
     *
     * @return the value of teacher.e-mail
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.e-mail
     *
     * @param eMail the value for teacher.e-mail
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.delete
     *
     * @return the value of teacher.delete
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.delete
     *
     * @param delete the value for teacher.delete
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setDelete(String delete) {
        this.delete = delete == null ? null : delete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.mode
     *
     * @return the value of teacher.mode
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.mode
     *
     * @param mode the value for teacher.mode
     *
     * @mbg.generated Tue Apr 14 16:30:53 CST 2020
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }
}