package com.as.dataobject;

public class UserPassword {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.userId
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.password
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.mode
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    private String mode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.userId
     *
     * @return the value of user_password.userId
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.userId
     *
     * @param userid the value for user_password.userId
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.id
     *
     * @return the value of user_password.id
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.id
     *
     * @param id the value for user_password.id
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.password
     *
     * @return the value of user_password.password
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.password
     *
     * @param password the value for user_password.password
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.mode
     *
     * @return the value of user_password.mode
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.mode
     *
     * @param mode the value for user_password.mode
     *
     * @mbg.generated Mon Apr 20 13:21:32 CST 2020
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }
}